### ISSUE TITLE
Relay server for P2P communications

### ISSUE THREAD

**Issue by mid-kid** [REONTeam/libmobile#7]
Currently, so people can play with eachother, they need to open the relevant port on their router, to receive connections from the exterior.

This isn't pretty or user-friendly at all, so let's explore some alternatives.

Generally, peer to peer software will use something called [UDP hole punching](https://en.wikipedia.org/wiki/UDP_hole_punching) to open a connection between two clients behind a NAT. This, however, is pretty complicated, requiring a discovery server in the middle.

Since the Mobile Adapter connections don't really need blazing speeds, and we need to have a server in the middle anyway, it might be worth relaying these connections through a central server. This is pretty inefficient and won't work very well with a critical volume of players, but will work just fine for how small the expected playerbase is. Additionally, this will allow us to assign and resolve phone numbers/handle some form of authentication.

**Comment by InternalLoss** [comment]
I think a relay server in the middle would make most sense, especially since we could then use fake numbers as mentioned; REON already has a field for these in user accounts.

We would likely be able to handle a few thousand if not more users at one time without any bandwidth problems, so I'm not too concerned about the relay becoming overwhelmed - we could always throttle each connection anyway to stop bad actors

**Comment by mid-kid** [comment]
This feature has been implemented as of v0.2.0:
https://github.com/REONTeam/libmobile/releases/tag/v0.2.0
https://github.com/REONTeam/mobile-relay/
